11주차: 24장 클로저
deep-dive-to-js/study-js-deep-dive pull request #52
Opened 2023-10-16 16:51 UTC by dev-hamster

## 작업 내용 (Content)
- 24장 클로저

## 링크 (Links)
- #51 

## 기타 사항 (Etc)
- 

## Merge 전 필요 작업 (Checklist before merge)
- N/A

2023-10-16 23:57 UTC, minjj0905 approved these changes
클로저에 조금 더 클로우즈 해진 기분

2023-10-16 23:57 UTC, parkyolo reviewed
25장과 26장이 기대되네요

2023-10-16 23:57 UTC, beomxtone requested changes

2023-10-16 23:57 UTC, beomxtone commented on week11/24_클로저.md
> +**함수가 선언된 렉시컬 환경아란?**
FIXME: 아란 -> 이란

2023-10-16 23:57 UTC, beomxtone commented on week11/24_클로저.md
> +  const inner = funtion() { console.log(x); } // (2)
FIXME: funtion -> function

2023-10-16 23:57 UTC, beomxtone commented on week11/24_클로저.md
> +중첩 함수가 상위 스코프의 식별자를 참조하고 있고 중첩 함수가 외부 함수보돠 더 오래 유지되는 경우를 말한다.
FIXME: 보돠 -> 보다

2023-10-16 23:57 UTC, beomxtone commented on week11/24_클로저.md
> +여기서 클로저에 의해 참조되는 상위 스코프이 변수를 자유 변수라고 부른다.
FIXME: 스코프이 -> 스코프의

2023-10-16 23:57 UTC, beomxtone commented on week11/24_클로저.md
> +increase와 decrease는 함수 정의가 평가되어 함수 객체가 될 때 실행 중인 실행 컨텍스트인 즉시 실행 컨텍스트의 렉시컬 환경을 기억하는 클로저이다. 그래서 increase와 decrease만이 자유 변수 num의 값을 변경할 수 있다.
FIXME: ?

2023-10-16 23:57 UTC, beomxtone commented on week11/24_클로저.md
> +function makeCounter(){
FIXME: 즉시 실행 함수로 변경

2023-10-16 23:57 UTC, beomxtone commented on week11/24_클로저.md
> +```jsx
FIXME: age 참조 문제, return 추가, } 삭제

2023-10-16 23:57 UTC, beomxtone commented on week11/24_클로저.md
> +상위 스코프애 즉시 시행 함수의 실행 컨텍스트의 렉시컬 환경이 저장된다.
FIXME: 스코프애 -> 스코프에

2023-10-16 23:57 UTC, beomxtone commented on week11/24_클로저.md
> +let이나 const 키워드를 사용하는 반복문은 코드 블록을 반복 실행할 떄마다 새로운 렉시컬 환경을 생성한다.
FIXME: 떄 x2 -> 때

2023-10-17 00:14 UTC, beomxtone approved these changes
고생하셨습니다 🙏🏻

2023-10-17 00:15 UTC, merged