15주차 28. Number ~ 30. Date
deep-dive-to-js/study-js-deep-dive pull request #68
Opened 2023-11-16 08:19 UTC by dev-hamster

## 작업 내용 (Content)
- 15주차 28. Number ~ 30. Date 

## 링크 (Links)
- https://github.com/deep-dive-to-js/study-js-deep-dive/issues/66

## 기타 사항 (Etc)
- N/A

## Merge 전 필요 작업 (Checklist before merge)
- N/A

2023-11-16 09:31 UTC, beomxtone requested changes
고생하셨습니다

2023-11-16 09:31 UTC, beomxtone commented on week15/28_Number.md
> +이때, 인수를 수자로 변환할 수 없으면 NaN을 [[NumberData]] 내부 슬롯에 할당한 Number 래퍼 객체를 생성함
FIXME: 수자 -> 숫자

2023-11-16 09:31 UTC, beomxtone commented on week15/28_Number.md
> +	return Math.abs(a-b) < Number.EPSLION;
FIXME: EPSLION to EPSILON

2023-11-16 09:31 UTC, beomxtone commented on week15/28_Number.md
> +Number.MIN_SAFE_INTEGER; // -9007199254740991
FIXME: delete last 1

2023-11-16 09:31 UTC, beomxtone commented on week15/28_Number.md
> +숫자를 지수 표기법으로 변환해 문자여 반환함.
FIXME: 문자여 to 문자열

2023-11-16 09:31 UTC, beomxtone commented on week15/28_Number.md
> +(100.12345).toExponential**(2); // '1.00e+2'**
FIXME: ?

2023-11-16 09:31 UTC, beomxtone commented on week15/28_Number.md
> +// 100은 Numbera 래퍼 객체임
FIXME: Numbera to Number

2023-11-16 09:31 UTC, beomxtone commented on week15/29_Math.md
> +Math.abs(undefinted); // NaN
FIXME: undefinted to undefined

2023-11-16 09:31 UTC, beomxtone commented on week15/29_Math.md
> +인수로 전달된 숫자의 소수점 이하를 **내림**한 정수를 반환하다. Math.ceil 메서드의 반대 개념이다.
FIXME: 반환하다 to 반환한다

2023-11-16 09:31 UTC, beomxtone commented on week15/30_Date.md
> +UTC(협정 세계시): 국제 표준시. GMT(그리나치 평균시)라고 부르기도 함. UTC와 GMT는 초의 소수점 단위에서만 차이가 나기 때문에 일상에서는 혼용되어 사용된다. 기술적인 표기에서는 UTC가 사용된다.
FIXME: 그리나치 to 그리니치

2023-11-16 09:31 UTC, beomxtone commented on week15/30_Date.md
> +예를들어 1970년 1월 2일 0시를 나타내는 Date 객체는 내부적으로 정수값 86,400,000(24h * 60m * 60s * 100ms)을 갖는다.
FIXME: 100ms to 1000ms

2023-11-16 09:31 UTC, beomxtone commented on week15/30_Date.md
> +new Date(); // "Sun Nov 12 2023 19:12:17 GMT+0900 (한국 표준시)"
FIXME: delete new

2023-11-16 09:31 UTC, beomxtone commented on week15/30_Date.md
> +**Date.prototype.toTimeSTring**
FIXME: ST to St

2023-11-16 09:31 UTC, beomxtone commented on week15/30_Date.md
> +today.toLocalString(); // 2020. 7. 24 오후 12:30:00
FIXME: Local to Locale

2023-11-16 09:31 UTC, beomxtone commented on week15/30_Date.md
> +today.toLocalTimeString(); // 오후 12:30:00
FIXME: Local to Locale

2023-11-16 09:32 UTC, minjj0905 approved these changes
자료형에 많은 메서드가,,,☝️

2023-11-27 05:46 UTC, jiyoungit approved these changes
쨔스의 다양한 메서드 잘 배워갑니다 👍🏻

2023-11-27 09:53 UTC, beomxtone approved these changes
고생하셨습니다

2023-11-27 09:53 UTC, merged