17주차: 33장 Symbol ~ 34장 이터러블
deep-dive-to-js/study-js-deep-dive pull request #76
Opened 2023-11-28 07:46 UTC by dev-hamster

## 작업 내용 (Content)
- 17주차 퀴즈

## 링크 (Links)
- https://github.com/deep-dive-to-js/study-js-deep-dive/issues/74

## 기타 사항 (Etc)
- N/A

## Merge 전 필요 작업 (Checklist before merge)
- N/A

2023-11-28 09:49 UTC, beomxtone requested changes
고생하셨습니다

2023-11-28 09:49 UTC, beomxtone commented on week17/33_Symbol.md
> +console.log(typeof mySymbol()); // symbol
FIXME: delete ()

2023-11-28 09:49 UTC, beomxtone commented on week17/33_Symbol.md
> +// 전역 심벌 레지스토리에 '킹왕짱 졸려'라는 키로 저장된 심벌 값이 ㅇ ㅓㅂㅅ으면 새로운 심벌 값을 생성
FIXME: ㅇ ㅓㅂㅅ to 없

2023-11-28 09:49 UTC, beomxtone commented on week17/33_Symbol.md
> +	[Symbol.for('mySymbol'): 1
FIXME: close bracket

2023-11-28 09:49 UTC, beomxtone commented on week17/34_이터러블.md
> +for…in**:**
FIXME: delete **

2023-11-28 09:49 UTC, beomxtone commented on week17/34_이터러블.md
> +	// next 메서드는 resut 객체를 반환한다.
FIXME: resut to result

2023-11-28 09:49 UTC, beomxtone commented on week17/34_이터러블.md
> +// 이터러블인 finonacci객체를 순회할 때마다 next 메서드가 호출된다.
FIXME: finonacci to fibonacci

2023-11-28 09:49 UTC, beomxtone commented on week17/34_이터러블.md
> +for (const num of finbonacci(10)){
FIXME: finbonacci to fibonacci

2023-11-28 09:49 UTC, beomxtone commented on week17/34_이터러블.md
> +const iterable = finboacci(5);
FIXME: finbonacci to fibonacci

2023-11-28 09:49 UTC, beomxtone commented on week17/34_이터러블.md
> +이터러블은 지연 평가를 통해 데이터를 생서한다. 지연 평가는 데이터가 필요한 시점이 되면 데이터를 생성하는 기법이다.
FIXME: 생서 to 생성

2023-11-28 09:49 UTC, minjj0905 approved these changes
js 스터디의 symbol 이 되고파요 😢

2023-12-12 08:30 UTC, beomxtone approved these changes
고생하셨습니다

2023-12-12 08:30 UTC, merged