23주차: 42장 비동기 프로그래밍
deep-dive-to-js/study-js-deep-dive pull request #98
Opened 2024-01-16 08:05 UTC by parkyolo

## 작업 내용 (Content)
- 42장 비동기 프로그래밍

## 링크 (Links)
- https://github.com/deep-dive-to-js/study-js-deep-dive/issues/95

## 기타 사항 (Etc)
- N/A

## Merge 전 필요 작업 (Checklist before merge)
- N/A

2024-01-16 10:36 UTC, dev-hamster requested changes

2024-01-16 10:36 UTC, dev-hamster commented on week23/42_비동기 프로그래밍.md
> +**비동기 처리에서 소스코드의 평과와 실행을 제외한 모든 처리**는 자바스크립트 엔진을 구동하는 환경인 **브라우저 또는 Node.js가 담당**한다.
fixme 평과

2024-01-16 10:43 UTC, dev-hamster commented
콜백,,,,, HELL,,,

2024-01-16 10:43 UTC, beomxtone approved these changes
실행중인실행컨텍스트가실행컨텍스트스택에들어가고실행컨텍스트스택은콜스택이군요

2024-01-31 07:34 UTC, dev-hamster approved these changes

2024-01-31 07:39 UTC, merged