23주차: 43장 Ajax
deep-dive-to-js/study-js-deep-dive pull request #99
Opened 2024-01-16 08:06 UTC by parkyolo

## 작업 내용 (Content)
- 43장 Ajax

## 링크 (Links)
- https://github.com/deep-dive-to-js/study-js-deep-dive/issues/95

## 기타 사항 (Etc)
- N/A

## Merge 전 필요 작업 (Checklist before merge)
- N/A

2024-01-16 11:02 UTC, dev-hamster requested changes

2024-01-16 11:02 UTC, dev-hamster commented on week23/43_Ajax.md
> +  |**onload**|HTTP 요청이 성공적으로 완료하나 경우|
fixme ㅇㅘㄴ료하나

2024-01-16 11:04 UTC, dev-hamster requested changes

2024-01-16 11:04 UTC, dev-hamster commented on week23/43_Ajax.md
> +  |GET|index/retrieve|모든/특저어 리소스 취득|X|
fixme 특저어

2024-01-16 11:06 UTC, dev-hamster requested changes

2024-01-16 11:06 UTC, dev-hamster commented on week23/43_Ajax.md
> +  ````jsx
fixme 네개

2024-01-16 11:11 UTC, beomxtone approved these changes
fetch를 많이 씁시다

2024-01-16 11:11 UTC, beomxtone commented on week23/43_Ajax.md
> +    // {userId: 1, id: 1, title: "delectus aut autem", complted:false}
fixme: complted to completed

2024-01-16 11:11 UTC, dev-hamster commented
O.O >-< 깜빡

2024-01-31 07:34 UTC, dev-hamster approved these changes

2024-01-31 07:39 UTC, merged